on:
  script:
    config:
      every: 35 * * * *
    run: |
      return [{title:"digest",time:new Date(),id:Date.now()}]
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            定时推送3：

            *${{on.script.outputs.title}}*
            
            ${{on.script.outputs.time}}
          format: markdown
