on:
  reddit:
    url: https://www.reddit.com/r/stocks/top/
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Translate to ZH
        id: translate
        uses: fabasoad/translation-action@main
        with:
          provider: microsoft
          api_key: ${{ secrets.MICROSOFT_TRANSLATE_API_KEY }}
          lang: 'zh-Hans'
          api_additional_parameter: westus2
          source: ${{ on.reddit.outputs.title}}
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <b>Stock:</b> <a href="${{on.reddit.outputs.link}}">${{ steps.translate.outputs.text}}</a>
          format: html
