on:
  reddit:
    url: https://www.reddit.com/r/stocks/top/
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Translate to ZH
        id: translate
        uses: theowenyoung/translation-action@main
        with:
          provider: tencent
          api_key: ${{ secrets.TENCENT_TRANSLATION_SECRET_KEY }}
          lang: 'zh'
          api_additional_parameter: ${{ secrets.TENCENT_TRANSLATION_SECRET_ID }}
          source: ${{ on.reddit.outputs.title}}
          api_additional_parameter2: na-siliconvalley
          api_additional_parameter3: en
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <b>Stock:</b> <a href="${{on.reddit.outputs.link}}">${{ steps.translate.outputs.text}}</a>
          format: html
