on:
  telegram_bot:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: ${{ toJSON(on.telegram_bot.outputs) }}
        run: |
          echo outputs: $outputs