on:
  script:
    config:
      active: false
      debug: true
      force: true
    run: |
      return [{title:"test",id:"1",selftext_html:'hello , <a href="https://baidu.com">baidu</a>'}]
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls /home/runner/work/workflow-for-test/workflow-for-test -l
      - name: Format reddit JSON
        env:
          OUTPUTS_PATH: /home/runner/work/workflow-for-test/workflow-for-test/test-data/reddit.json
        uses: ./.github/actions/format
        with:
          function: reddit
