on:
  script:
    config:
      force: true
      skipSchedule: true
      manualRunEvent: 
        - workflow_dispatch
        - push
    run: |
      return [{title:"test",id:"1"}]
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: -1001462218950
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            channel:
            *${{on.script.outputs.title}}*
          format: markdown
