on:
  script:
    config:
      active: true
      debug: true
    run: |
      return [{title:"test",id:"1",selftext_html:'hello , <a href="https://baidu.com">baidu</a>'}]
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Format reddit JSON
        env:
          OUTPUTS_PATH: ${{ on.reddit.outputs.path }}
        uses: ./.github/actions/format
        with:
          function: reddit
