on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: theowenyoung
    fetchAllResultsAtFirst: true
    config:
      active: true
      force: true
      outputsMode: combine
      manualRunEvent:
        - workflow_dispatch
        - push
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: ls -l data/tweets
      - name: create tweet json
        id: create-json
        uses: actions/github-script@v3
        with:
          script: |
            const path = requrie('path')
            const fs = require('fs').promises
            const outputs = ${{toJSON(on.twitter.outputs)}}
            const promises = outputs.map((output) => {
                const createdAt = new Date(Date.parse(output.created_at))
                const tweetFilePath = `./data/tweets/${createdAt.getFullYear()}/${createdAt.getFullMonth()}/${output.id_str}.json`
                await fs.mkdir(path.dirname(tweetFilePath), {
                    recursive: true
                });
                return fs.writeFile(
                    tweetFilePath,
                    JSON.stringify(output, null, 2)
                );
            });
            await Promise.all(promises);
            return outputs.length
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore: add tweet data"
          add: "data/tweets/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}