on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: theowenyoung
      count: 4
    fetchAllResultsAtFirst: true
    maxCount: 4
    config:
      force: true
      manualRunEvent:
        - workflow_dispatch
        - push
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: create tweet json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "${{ on.twitter.outputs.id_str }}.json"
          json: ${{ toJSON(on.twitter.outputs) }}
          dir: 'data/tweets'
      - uses: actions-go/push@master
        with:
          commit-message: '[Auto] update pre-puilt dist packages'
        remote: origin
      - name: Setup git
        if: false
        run: apt update -y && apt install -y git-all
      - name: Configure CI Git User
        if: false
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Git Push
        if: false
        run: |
          git remote -v
          git status
          git add data/*
          git commit -m "chore: update tweet data"
          git push origin main