on:
  webhook:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: ${{ toJSON(on.webhook.outputs)}}
        run: |
          echo outputs: $outputs
