name: Send a telegram message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCnCikd0s4i9KoDtaHPlK-JA
      - UCseUQK4kC3x2x543nHtGpzw
    playlist_id:
      - PL99D544ED5B1E58D8
      - PL2qc-hH9Ip-SSUaZd_G8IxtecK0WZ-af-
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.0.8
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: |
            <b>${{ on.youtube.outputs.title }}</b>
            <br>
            ${{ on.youtube.outputs.description }}
            <br>
            ${{ on.youtube.outputs.link}}
